import type { Metadata } from "next";
// import { Geist, Geist_Mono, Local } from "next/font/google";
import localFont from 'next/font/local'

import "./globals.css";
import Provider from "@/providers";


const SariaStencilFont = localFont({
  src: [
    {
      path: '../public/fonts/SairaStencil-Italic-VariableFont_wdth,wght.ttf',
      weight: '400',
      style: 'italic'
    },
    {
      path: '../public/fonts/SairaStencil-VariableFont_wdth,wght.ttf',
      weight: '500',
      style: 'normal'
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${SariaStencilFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Provider>
          {children}
          {/* <BackgroundBeamsDemo/> */}
        </Provider>
      </body>
    </html>
  );
}
